# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -AhlF'
alias la='ls -A'
alias l='ls -CF'

alias ffprobe="ffprobe -hide_banner"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias vnctunnel='ssh -L 5902:lxcms00:5902 amecca@lxplus.cern.ch'
TBrowser() { root -l $@ -e "TBrowser b;" ; }
rootls(){ root -l $@ -e "_file0->ls()" -q; }
opennull(){ open "$1" &>/dev/null ; }

# alias notify-permanent="notify-send -u critical -i dialog-information"
# function monitor-ssh-notify {
# 	 [ $# -eq 1 ] || { echo "Error: remote machine name required" ; return 1 ; }
# 	 ssh "$1" 'rm -f /tmp/amecca/alert_fifo ; mkfifo /tmp/amecca/alert_fifo ; while cat /tmp/amecca/alert_fifo ; do sleep 5 ; done' |\
# 	     while read text ; do
# 	     	   notify-permanent "${text%%|*}" "${text#*|}"
# 	     done
# }

alias cernOTP="oathtool -b --totp=SHA1   @$HOME/.local/share/secret_CERN | tr -d '\n' | xclip -sel clip"
alias infnOTP="oathtool -b --totp=SHA256 @$HOME/.local/share/secret_INFN | tr -d '\n' | xclip -sel clip"
